### ISSUE TITLE
Won't compile under Xcode 7.3

### ISSUE THREAD

**Issue by JetForMe** [dmauro/WeakArray#4]
I think they changed some things about the language; it doesn't seem to compile any more.

WeakArray.swift
WeakArray.swift:76:54: 'Printable' has been renamed to 'CustomStringConvertible'
WeakArray.swift:76:65: 'DebugPrintable' has been renamed to 'CustomDebugStringConvertible'
WeakArray.swift:29:35: Type 'T?' does not conform to protocol 'Indexable'
WeakArray.swift:43:35: Type 'T?' does not conform to protocol 'Indexable'
WeakArray.swift:131:44: Type 'T?' does not conform to protocol 'Indexable'
WeakArray.swift:173:79: Type 'T?' does not conform to protocol 'Indexable'
WeakArray.swift:178:46: Type 'T?' does not conform to protocol 'Indexable'
WeakArray.swift:183:46: Type 'T?' does not conform to protocol 'Indexable'
WeakArray.swift:212:24: Type 'T?' does not conform to protocol 'Indexable'
WeakArray.swift:112:17: Method cannot be declared public because its result uses a private type
WeakArray.swift:211:15: Type alias 'Element' must be declared public because it matches a requirement in public protocol 'GeneratorType'
WeakArray.swift:62:27: '?' must be followed by a call, member lookup, or subscript
WeakArray.swift:113:24: Type 'Weak<T>' does not conform to protocol 'Indexable'
WeakArray.swift:114:20: Type 'T?' does not conform to protocol 'Indexable'
WeakArray.swift:133:28: Type 'Weak<T>' does not conform to protocol 'Indexable'
WeakArray.swift:134:24: Type 'T?' does not conform to protocol 'Indexable'

**Comment by dmauro** [comment]
Yeah sorry, I haven't kept up with this. Collection protocols have changed significantly since I last touched it and I actually would need to do a LOT of research into how they work behind the scenes now to get it working again. I might tackle it, but for now this repo is effectively dead. Sorry :(
